@echo off
echo Starting development environment...
echo.
echo 1. Starting API server on port 3001...
start "API Server" cmd /k "npm run dev:api"
echo.
echo 2. Waiting 3 seconds for API server to start...
timeout /t 3 /nobreak > nul
echo.
echo 3. Starting Vite dev server on port 8080...
start "Vite Dev Server" cmd /k "npm run dev"
echo.
echo Both servers are starting...
echo API Server: http://localhost:3001
echo Dev Server: http://localhost:8080
echo.
echo Press any key to exit...
pause > nul
